### PR TITLE
creating CI version of harpocrates, so we don't have to install a bunch of stuff during CircleCI runs

### PR DESCRIPTION
**Pull request by Gaardsholt**
Basically to avoid stuff like this: https://app.circleci.com/pipelines/github/BESTSELLER/backstage/2923/workflows/f937d804-10e0-45c5-8a27-ea5525b37290/jobs/8916

### CODE REVIEW

**Comment by Andrei-Predoiu** [comment]
I just verified it @Gaardsholt. Looks good

**Review by Andrei-Predoiu — APPROVED** [review]

**Comment by Gaardsholt** [comment]
> I just verified it @Gaardsholt. Looks good

I'm guessing this was the wrong PR you commented on? ;)

**Comment by Andrei-Predoiu** [comment]
> > I just verified it @Gaardsholt. Looks good
> 
> I'm guessing this was the wrong PR you commented on? ;)

Yes, was supposed to be for gke :D

**Review by dennisc87 — APPROVED** [review]
LGTM

**Review by brondum — APPROVED** [review]

**Pull request merged**
